Add Detekt for static code analysis and update pre-commit hook

diff --git a/scripts/pre-commit b/scripts/pre-commit
--- a/scripts/pre-commit
+++ b/scripts/pre-commit
@@ -3,12 +3,15 @@
 echo "Running git pre-commit hook"
 
 ./gradlew ktlintCheck
-
 ktlintCheckStatus=$?
 
-# return 1 if check fails
-if [[ $ktlintCheckStatus -ne 0 ]]; then
-     exit 1
+./gradlew detekt
+detektStatus=$?
+
+# return 1 if any check fails
+if [[ $ktlintCheckStatus -ne 0 || $detektStatus -ne 0 ]]; then
+    echo "Code style violations or code issues found. Please fix them before committing."
+    exit 1
 else
-     exit 0
+    exit 0
 fi
